name: Daglig aktierapport

on:
  schedule:
    - cron: '0 * * * 1-5'        # trigga varje hel timme på vardagar (UTC)
  workflow_dispatch: {}           # tillåt manuell körning

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      # --- Kör ENDAST 18:00 Stockholm (manual runs alltid tillåtna) ---
      - name: Run only at 18:00 Stockholm (manual runs always allowed)
        shell: bash
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "Manual run -> OK"
            exit 0
          fi
          sudo timedatectl set-timezone Europe/Stockholm
          H=$(date +%H)
          M=$(date +%M)
          D=$(date +%u)  # 1=Mon ... 5=Fri
          echo "Local time: $(date)"
          if [ "$D" -ge 1 ] && [ "$D" -le 5 ] && [ "$H" = "18" ] && [ "$M" = "00" ]; then
            echo "It's 18:00 Stockholm — proceed"
          else
            echo "Not 18:00 Stockholm — skipping"
            exit 78
          fi

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run report
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python run.py

      - name: Commit and push report
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add daily_reports/*.md top_lists.json || true
          git commit -m "EOD report $(date +'%Y-%m-%d')" || echo "Nothing to commit"
          git push
